게시글 생성, 조회 기능 추가
f-lab-edu/FastAPI-Board pull request #2
Opened 2024-06-25 14:38 UTC by Dongyeon1201

- 게시글 생성, 조회 기능 추가
- 게시글 관련 데이터(`Post`)의 스키마 추가
- poetry등을 활용한 환경설정

2024-06-28 06:53 UTC, f-lab-ydrah requested changes
`.idea/` 는 보통 깃허브에 올리지 않습니다. `.gitignore`를 활용해서 제외시켜 보시겠어요?

2024-06-28 06:53 UTC, f-lab-ydrah commented on main.py
> +@app.get("/", status_code=status.HTTP_200_OK)
굿. `fastapi.status` 써서 Status Code 표현하는거 시멘틱하고 명시적이어서 아주 좋아요.

2024-06-28 06:53 UTC, f-lab-ydrah commented on main.py
> +def read_root() -> dict:
```suggestion
def read_root() -> dict[str, str]:
```

위처럼 dict, list 등 element에도 type을 추가하곤 합니다 ㅎㅎ

2024-06-28 06:53 UTC, f-lab-ydrah commented on main.py
> +        raise HTTPException(status_code=404, detail="존재하지 않는 게시글입니다.")
여기도 `404` 대신 `fastapi.status` 모듈에 있는 상수 값 써주면 좀 더 일관된 코드가 되겠네요.

2024-06-28 06:53 UTC, f-lab-ydrah commented on main.py
> +        return post_data[post_id]
아이템을 리스트로 저장하면, 특정 아이템을 찾는데 시간 복잡도는 `O(n)` 이겠죠?
`O(1)` 로 줄여볼 순 없을까요?

2024-06-28 06:53 UTC, f-lab-ydrah commented on main.py
> +@app.post("/posts/", response_model=ResponsePost, status_code=status.HTTP_201_CREATED)
201 상태 코드 아주 좋습니다.

2024-06-28 06:53 UTC, f-lab-ydrah commented on main.py
> +def create_post(post: RequestPost):
반환 타입 타입 힌팅!

2024-06-28 06:53 UTC, f-lab-ydrah commented on schemas/post.py
> +    id: UUID = Field(default_factory=uuid4)
아이디를 uuid로 만드는 것 외에 보통 어떤 다른 방법도 있을까요?
다른 방법 외에 uuid로 만드신 이유가 있나요?

2024-06-28 06:53 UTC, f-lab-ydrah commented on schemas/post.py
> +    created_at: datetime = Field(default_factory=datetime.now)
파이썬에서 naive datetime과 aware datetime의 차이를 아시나요?
어떤 차이가 있고, 위 코드의 경우 둘 중 어느 것일까요?
추후에 글로벌 서비스를 생각한다면, 어떤 문제가 있을까요?

2024-06-28 06:53 UTC, f-lab-ydrah commented on schemas/post.py
> +    created_at: datetime = Field(default_factory=datetime.now)
보통 `created_at` 과 함께 업데이트 될 소지가 있는 경우, `updated_at` 도 필드로 추가합니다.

2024-06-29 10:22 UTC, Dongyeon1201 commented on main.py
> +def read_root() -> dict:
감사합니다 적용해보겠습니다 :)

2024-06-29 10:25 UTC, Dongyeon1201 commented on main.py
> +        return post_data[post_id]
처음에는 게시글의 id를 리스트의 index로 사용하였습니다.
그래서 조회 시에도 O(1)일 것 같아 위 코드로 작성했던 것 같습니다.

현재는 ID를 UUID로(바뀔수도 있습니다!) 설정했기 때문에, 해시테이블을 사용하는 방식으로 변경해보겠습니다!

2024-06-29 10:26 UTC, Dongyeon1201 commented on main.py
> +def create_post(post: RequestPost):
```python3
def create_post(post: RequestPost) -> Post:
```

으로 변경해보겠습니다 :)

2024-06-29 10:36 UTC, Dongyeon1201 commented on schemas/post.py
> +    id: UUID = Field(default_factory=uuid4)
**[ UUID를 사용한 이유 ]**
- 이전에 사용했던 리스트의 index 번호를 그대로 사용하는 것 보다 더 보안상 안전할 것 같았습니다.(외부 공개 데이터이기 때문에) index 번호를 그대로 사용하게 된다면, 규칙성 있는 번호가 ID로 적용되며 이는 다른 게시글의 비정상적인 참조가 가능할 것 같았습니다. 물론, 게시글 작성자 확인을 통한 방어가 가능합니다.
- 추가적으로 찾아본 내용으로는 단일 DB가 아닌 여러 DB를 사용하는 경우에도 고유한 데이터로 관리가 가능하기 때문이라는 장점도 알게 되었습니다.
- 하지만, UUID는 index번호 사용 방식에 비해 각 ID의 데이터가 더 큰 편이며 이는 더 많은 리소스의 사용을 부를 수 있을 것 같았습니다.
- 현재 프로젝트에서는 단점에 대해 크게 신경쓰지 않아도 될 것 같아, UUID를 사용하게 되었습니다.

**[ UUID 외 다른 방법 ]**
- 처음 사용하였던 양의 정수를 사용하여 순차적으로 증가하는 idx를 설정하는 방법이 있습니다
- 해시를 사용한 ID

2024-06-29 10:38 UTC, Dongyeon1201 commented on schemas/post.py
> +    created_at: datetime = Field(default_factory=datetime.now)
**[ naive datetime와 aware datetime의 차이 ]**
- 저장되는 데이터의 TimeZone 존재 여부입니다.
- 글로벌 서비스를 생각한다면, UTC를 표준으로 사용하며 각 나라별로 다른 Timezone을 적용할 수 있는 aware datetime을 사용하는 것이 더 좋을 것 같습니다.

2024-06-29 12:35 UTC, Dongyeon1201 commented on schemas/post.py
> +    created_at: datetime = Field(default_factory=datetime.now)
aware datetime 적용 내용관련 커밋입니다 :)
https://github.com/f-lab-edu/FastAPI-Board/pull/2/commits/367f76b5bfdf8297f55d3975bef1e66d5368c7a5

2024-06-30 23:44 UTC, f-lab-ydrah commented on schemas/post.py
> +    id: UUID = Field(default_factory=uuid4)
RDB를 사용할 때, 프라이머리 키로 UUID 방식을 선택하는 경우, auto increment 방식에 비해 삽입 속도가 조금 느려집니다.
이에 대한 이유는 구글링으로 한번 찾아보셔요 ㅎ_ㅎ 찾아서 읽어볼만한 가치가 있습니다.

엔티티 아이디 생성 문제는 늘 뜨거운 이슈 + 시스템 디자인에도 종종 나오는 문제인데, 어떤 방법들이 있나 살펴보셔요!

2024-06-30 23:44 UTC, f-lab-ydrah approved these changes
👍

2024-07-02 03:58 UTC, merged